### ISSUE TITLE
Update to Bevy 0.13

### ISSUE THREAD

**Issue by alepez** [alepez/lavagna#26]
Update the game engine to Bevy 0.13 once all required plugins have become compatible with that version.

- [x] [bevy_embedded_assets](https://github.com/vleue/bevy_embedded_assets)
- [x] [bevy_framepace](https://github.com/aevyrie/bevy_framepace)
- [x] [bevy_pancam](https://github.com/johanhelsing/bevy_pancam)
- [x] [bevy_prototype_lyon](https://github.com/Nilirad/bevy_prototype_lyon)
- [x] [bevy_ggrs](https://github.com/gschup/bevy_ggrs)
- [x] [bevy_matchbox](https://github.com/johanhelsing/matchbox)

**Comment by alepez** [comment]
Check:

- https://github.com/gschup/bevy_ggrs/issues/105
- https://github.com/gschup/bevy_ggrs/pull/106
- https://github.com/johanhelsing/matchbox/issues/419

**Comment by patowen** [comment]
I just noticed that this issue never got auto-resolved. We should probably close it now that the PR has been merged.
